version: 0.2

phases:
  install:
    commands:
      - echo "Installing Amazon Corretto 19..."
      - wget https://corretto.aws/downloads/latest/amazon-corretto-19-x64-linux-jdk.tar.gz
      - tar -xzf amazon-corretto-19-x64-linux-jdk.tar.gz
      - sudo mkdir -p /usr/lib/jvm/
      - sudo mv amazon-corretto-19.0.2.7.1-linux-x64 /usr/lib/jvm/java-19-amazon-corretto
      - echo 'export JAVA_HOME=/usr/lib/jvm/java-19-amazon-corretto' >> ~/.bash_profile
      - echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bash_profile
      - source ~/.bash_profile  # Ensure environment variables are set
      - java -version  # Verify Java installation
      - sudo yum install maven -y

  build:
    commands:
      - echo "Building the application..."
      - mvn clean install

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - src/**/*
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: no 
